print('Hello Tiltfile')

k8s_yaml('platforms-deployment.yaml')
k8s_yaml('commands-deployment.yaml')
k8s_yaml('mssql-platform-deployment.yaml')
k8s_yaml('rabbitmq-deployment.yaml')
k8s_yaml('ingress-srv.yaml')
k8s_yaml('local-pvc.yaml')
k8s_yaml('platforms-np-srv.yaml')

docker_build('kenamier/platformservice', '../PlatformService/')
docker_build('kenamier/commandservice', '../CommandsService/')
